apiVersion: apps/v1
kind: Deployment
metadata:
  name: svelte-websocket-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: svelte-websocket-ui
  template:
    metadata:
      labels:
        app: svelte-websocket-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: svelte-websocket-ui
        ports:
        - containerPort: 80
